// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp-cost.proto

package com.emarbox.dsp.api.domain;

public final class DspCost {
  private DspCost() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DspCostInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 campaignId = 3;
    boolean hasCampaignId();
    long getCampaignId();
    
    // optional double cost = 4;
    boolean hasCost();
    double getCost();
    
    // optional int64 supplierId = 5;
    boolean hasSupplierId();
    long getSupplierId();
    
    // optional string date = 6;
    boolean hasDate();
    String getDate();
    
    // optional int32 hour = 7;
    boolean hasHour();
    int getHour();
    
    // optional int32 minute = 8;
    boolean hasMinute();
    int getMinute();
    
    // optional int64 clickCount = 9;
    boolean hasClickCount();
    long getClickCount();
    
    // optional int64 impressionCount = 10;
    boolean hasImpressionCount();
    long getImpressionCount();
    
    // optional double biddingCost = 11;
    boolean hasBiddingCost();
    double getBiddingCost();
    
    // optional double rtbCost = 12;
    boolean hasRtbCost();
    double getRtbCost();
  }
  public static final class DspCostInfo extends
      com.google.protobuf.GeneratedMessage
      implements DspCostInfoOrBuilder {
    // Use DspCostInfo.newBuilder() to construct.
    private DspCostInfo(Builder builder) {
      super(builder);
    }
    private DspCostInfo(boolean noInit) {}
    
    private static final DspCostInfo defaultInstance;
    public static DspCostInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public DspCostInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emarbox.dsp.api.domain.DspCost.internal_static_campaign_DspCostInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emarbox.dsp.api.domain.DspCost.internal_static_campaign_DspCostInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 campaignId = 3;
    public static final int CAMPAIGNID_FIELD_NUMBER = 3;
    private long campaignId_;
    public boolean hasCampaignId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getCampaignId() {
      return campaignId_;
    }
    
    // optional double cost = 4;
    public static final int COST_FIELD_NUMBER = 4;
    private double cost_;
    public boolean hasCost() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getCost() {
      return cost_;
    }
    
    // optional int64 supplierId = 5;
    public static final int SUPPLIERID_FIELD_NUMBER = 5;
    private long supplierId_;
    public boolean hasSupplierId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getSupplierId() {
      return supplierId_;
    }
    
    // optional string date = 6;
    public static final int DATE_FIELD_NUMBER = 6;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 hour = 7;
    public static final int HOUR_FIELD_NUMBER = 7;
    private int hour_;
    public boolean hasHour() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getHour() {
      return hour_;
    }
    
    // optional int32 minute = 8;
    public static final int MINUTE_FIELD_NUMBER = 8;
    private int minute_;
    public boolean hasMinute() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getMinute() {
      return minute_;
    }
    
    // optional int64 clickCount = 9;
    public static final int CLICKCOUNT_FIELD_NUMBER = 9;
    private long clickCount_;
    public boolean hasClickCount() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getClickCount() {
      return clickCount_;
    }
    
    // optional int64 impressionCount = 10;
    public static final int IMPRESSIONCOUNT_FIELD_NUMBER = 10;
    private long impressionCount_;
    public boolean hasImpressionCount() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getImpressionCount() {
      return impressionCount_;
    }
    
    // optional double biddingCost = 11;
    public static final int BIDDINGCOST_FIELD_NUMBER = 11;
    private double biddingCost_;
    public boolean hasBiddingCost() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public double getBiddingCost() {
      return biddingCost_;
    }
    
    // optional double rtbCost = 12;
    public static final int RTBCOST_FIELD_NUMBER = 12;
    private double rtbCost_;
    public boolean hasRtbCost() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public double getRtbCost() {
      return rtbCost_;
    }
    
    private void initFields() {
      campaignId_ = 0L;
      cost_ = 0D;
      supplierId_ = 0L;
      date_ = "";
      hour_ = 0;
      minute_ = 0;
      clickCount_ = 0L;
      impressionCount_ = 0L;
      biddingCost_ = 0D;
      rtbCost_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCampaignId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(3, campaignId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(4, cost_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(5, supplierId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(6, getDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(7, hour_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(8, minute_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(9, clickCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(10, impressionCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(11, biddingCost_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(12, rtbCost_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, campaignId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, cost_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, supplierId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, hour_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, minute_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, clickCount_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, impressionCount_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, biddingCost_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, rtbCost_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCost.DspCostInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.emarbox.dsp.api.domain.DspCost.DspCostInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.emarbox.dsp.api.domain.DspCost.internal_static_campaign_DspCostInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.emarbox.dsp.api.domain.DspCost.internal_static_campaign_DspCostInfo_fieldAccessorTable;
      }
      
      // Construct using com.emarbox.dsp.api.domain.DspCost.DspCostInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        campaignId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        cost_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        supplierId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        hour_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        minute_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        clickCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        impressionCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        biddingCost_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        rtbCost_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.emarbox.dsp.api.domain.DspCost.DspCostInfo.getDescriptor();
      }
      
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfo getDefaultInstanceForType() {
        return com.emarbox.dsp.api.domain.DspCost.DspCostInfo.getDefaultInstance();
      }
      
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfo build() {
        com.emarbox.dsp.api.domain.DspCost.DspCostInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.emarbox.dsp.api.domain.DspCost.DspCostInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.emarbox.dsp.api.domain.DspCost.DspCostInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfo buildPartial() {
        com.emarbox.dsp.api.domain.DspCost.DspCostInfo result = new com.emarbox.dsp.api.domain.DspCost.DspCostInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.campaignId_ = campaignId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cost_ = cost_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.supplierId_ = supplierId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hour_ = hour_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.minute_ = minute_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.clickCount_ = clickCount_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.impressionCount_ = impressionCount_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.biddingCost_ = biddingCost_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.rtbCost_ = rtbCost_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.emarbox.dsp.api.domain.DspCost.DspCostInfo) {
          return mergeFrom((com.emarbox.dsp.api.domain.DspCost.DspCostInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.emarbox.dsp.api.domain.DspCost.DspCostInfo other) {
        if (other == com.emarbox.dsp.api.domain.DspCost.DspCostInfo.getDefaultInstance()) return this;
        if (other.hasCampaignId()) {
          setCampaignId(other.getCampaignId());
        }
        if (other.hasCost()) {
          setCost(other.getCost());
        }
        if (other.hasSupplierId()) {
          setSupplierId(other.getSupplierId());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasHour()) {
          setHour(other.getHour());
        }
        if (other.hasMinute()) {
          setMinute(other.getMinute());
        }
        if (other.hasClickCount()) {
          setClickCount(other.getClickCount());
        }
        if (other.hasImpressionCount()) {
          setImpressionCount(other.getImpressionCount());
        }
        if (other.hasBiddingCost()) {
          setBiddingCost(other.getBiddingCost());
        }
        if (other.hasRtbCost()) {
          setRtbCost(other.getRtbCost());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCampaignId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              campaignId_ = input.readInt64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000002;
              cost_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              supplierId_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000008;
              date_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              hour_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000020;
              minute_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000040;
              clickCount_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000080;
              impressionCount_ = input.readInt64();
              break;
            }
            case 89: {
              bitField0_ |= 0x00000100;
              biddingCost_ = input.readDouble();
              break;
            }
            case 97: {
              bitField0_ |= 0x00000200;
              rtbCost_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 campaignId = 3;
      private long campaignId_ ;
      public boolean hasCampaignId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getCampaignId() {
        return campaignId_;
      }
      public Builder setCampaignId(long value) {
        bitField0_ |= 0x00000001;
        campaignId_ = value;
        onChanged();
        return this;
      }
      public Builder clearCampaignId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        campaignId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double cost = 4;
      private double cost_ ;
      public boolean hasCost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getCost() {
        return cost_;
      }
      public Builder setCost(double value) {
        bitField0_ |= 0x00000002;
        cost_ = value;
        onChanged();
        return this;
      }
      public Builder clearCost() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cost_ = 0D;
        onChanged();
        return this;
      }
      
      // optional int64 supplierId = 5;
      private long supplierId_ ;
      public boolean hasSupplierId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getSupplierId() {
        return supplierId_;
      }
      public Builder setSupplierId(long value) {
        bitField0_ |= 0x00000004;
        supplierId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSupplierId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        supplierId_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string date = 6;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
      }
      
      // optional int32 hour = 7;
      private int hour_ ;
      public boolean hasHour() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getHour() {
        return hour_;
      }
      public Builder setHour(int value) {
        bitField0_ |= 0x00000010;
        hour_ = value;
        onChanged();
        return this;
      }
      public Builder clearHour() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hour_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 minute = 8;
      private int minute_ ;
      public boolean hasMinute() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getMinute() {
        return minute_;
      }
      public Builder setMinute(int value) {
        bitField0_ |= 0x00000020;
        minute_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinute() {
        bitField0_ = (bitField0_ & ~0x00000020);
        minute_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 clickCount = 9;
      private long clickCount_ ;
      public boolean hasClickCount() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getClickCount() {
        return clickCount_;
      }
      public Builder setClickCount(long value) {
        bitField0_ |= 0x00000040;
        clickCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearClickCount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        clickCount_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 impressionCount = 10;
      private long impressionCount_ ;
      public boolean hasImpressionCount() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getImpressionCount() {
        return impressionCount_;
      }
      public Builder setImpressionCount(long value) {
        bitField0_ |= 0x00000080;
        impressionCount_ = value;
        onChanged();
        return this;
      }
      public Builder clearImpressionCount() {
        bitField0_ = (bitField0_ & ~0x00000080);
        impressionCount_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double biddingCost = 11;
      private double biddingCost_ ;
      public boolean hasBiddingCost() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public double getBiddingCost() {
        return biddingCost_;
      }
      public Builder setBiddingCost(double value) {
        bitField0_ |= 0x00000100;
        biddingCost_ = value;
        onChanged();
        return this;
      }
      public Builder clearBiddingCost() {
        bitField0_ = (bitField0_ & ~0x00000100);
        biddingCost_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double rtbCost = 12;
      private double rtbCost_ ;
      public boolean hasRtbCost() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public double getRtbCost() {
        return rtbCost_;
      }
      public Builder setRtbCost(double value) {
        bitField0_ |= 0x00000200;
        rtbCost_ = value;
        onChanged();
        return this;
      }
      public Builder clearRtbCost() {
        bitField0_ = (bitField0_ & ~0x00000200);
        rtbCost_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:campaign.DspCostInfo)
    }
    
    static {
      defaultInstance = new DspCostInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:campaign.DspCostInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_DspCostInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_DspCostInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016dsp-cost.proto\022\010campaign\"\302\001\n\013DspCostIn" +
      "fo\022\022\n\ncampaignId\030\003 \002(\003\022\014\n\004cost\030\004 \001(\001\022\022\n\n" +
      "supplierId\030\005 \001(\003\022\014\n\004date\030\006 \001(\t\022\014\n\004hour\030\007" +
      " \001(\005\022\016\n\006minute\030\010 \001(\005\022\022\n\nclickCount\030\t \001(\003" +
      "\022\027\n\017impressionCount\030\n \001(\003\022\023\n\013biddingCost" +
      "\030\013 \001(\001\022\017\n\007rtbCost\030\014 \001(\001B%\n\032com.emarbox.d" +
      "sp.api.domainB\007DspCost"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_campaign_DspCostInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_campaign_DspCostInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_campaign_DspCostInfo_descriptor,
              new java.lang.String[] { "CampaignId", "Cost", "SupplierId", "Date", "Hour", "Minute", "ClickCount", "ImpressionCount", "BiddingCost", "RtbCost", },
              com.emarbox.dsp.api.domain.DspCost.DspCostInfo.class,
              com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
