// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dsp-cost-request.proto

package com.emarbox.dsp.api.domain;

public final class DspCostRequest {
  private DspCostRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DspCostRequestInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string nodeSign = 1;
    boolean hasNodeSign();
    String getNodeSign();
    
    // optional string batchCode = 2;
    boolean hasBatchCode();
    String getBatchCode();
    
    // optional string dataDate = 3;
    boolean hasDataDate();
    String getDataDate();
    
    // optional int64 dataHour = 4;
    boolean hasDataHour();
    long getDataHour();
    
    // optional string statTime = 5;
    boolean hasStatTime();
    String getStatTime();
    
    // repeated .campaign.DspCostInfo dspCost = 51;
    java.util.List<com.emarbox.dsp.api.domain.DspCost.DspCostInfo> 
        getDspCostList();
    com.emarbox.dsp.api.domain.DspCost.DspCostInfo getDspCost(int index);
    int getDspCostCount();
    java.util.List<? extends com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder> 
        getDspCostOrBuilderList();
    com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder getDspCostOrBuilder(
        int index);
  }
  public static final class DspCostRequestInfo extends
      com.google.protobuf.GeneratedMessage
      implements DspCostRequestInfoOrBuilder {
    // Use DspCostRequestInfo.newBuilder() to construct.
    private DspCostRequestInfo(Builder builder) {
      super(builder);
    }
    private DspCostRequestInfo(boolean noInit) {}
    
    private static final DspCostRequestInfo defaultInstance;
    public static DspCostRequestInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public DspCostRequestInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.emarbox.dsp.api.domain.DspCostRequest.internal_static_campaign_DspCostRequestInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.emarbox.dsp.api.domain.DspCostRequest.internal_static_campaign_DspCostRequestInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string nodeSign = 1;
    public static final int NODESIGN_FIELD_NUMBER = 1;
    private java.lang.Object nodeSign_;
    public boolean hasNodeSign() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNodeSign() {
      java.lang.Object ref = nodeSign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nodeSign_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNodeSignBytes() {
      java.lang.Object ref = nodeSign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nodeSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string batchCode = 2;
    public static final int BATCHCODE_FIELD_NUMBER = 2;
    private java.lang.Object batchCode_;
    public boolean hasBatchCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getBatchCode() {
      java.lang.Object ref = batchCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          batchCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBatchCodeBytes() {
      java.lang.Object ref = batchCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        batchCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string dataDate = 3;
    public static final int DATADATE_FIELD_NUMBER = 3;
    private java.lang.Object dataDate_;
    public boolean hasDataDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDataDate() {
      java.lang.Object ref = dataDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dataDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataDateBytes() {
      java.lang.Object ref = dataDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dataDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 dataHour = 4;
    public static final int DATAHOUR_FIELD_NUMBER = 4;
    private long dataHour_;
    public boolean hasDataHour() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getDataHour() {
      return dataHour_;
    }
    
    // optional string statTime = 5;
    public static final int STATTIME_FIELD_NUMBER = 5;
    private java.lang.Object statTime_;
    public boolean hasStatTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getStatTime() {
      java.lang.Object ref = statTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          statTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStatTimeBytes() {
      java.lang.Object ref = statTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        statTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .campaign.DspCostInfo dspCost = 51;
    public static final int DSPCOST_FIELD_NUMBER = 51;
    private java.util.List<com.emarbox.dsp.api.domain.DspCost.DspCostInfo> dspCost_;
    public java.util.List<com.emarbox.dsp.api.domain.DspCost.DspCostInfo> getDspCostList() {
      return dspCost_;
    }
    public java.util.List<? extends com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder> 
        getDspCostOrBuilderList() {
      return dspCost_;
    }
    public int getDspCostCount() {
      return dspCost_.size();
    }
    public com.emarbox.dsp.api.domain.DspCost.DspCostInfo getDspCost(int index) {
      return dspCost_.get(index);
    }
    public com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder getDspCostOrBuilder(
        int index) {
      return dspCost_.get(index);
    }
    
    private void initFields() {
      nodeSign_ = "";
      batchCode_ = "";
      dataDate_ = "";
      dataHour_ = 0L;
      statTime_ = "";
      dspCost_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getDspCostCount(); i++) {
        if (!getDspCost(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNodeSignBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBatchCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, dataHour_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getStatTimeBytes());
      }
      for (int i = 0; i < dspCost_.size(); i++) {
        output.writeMessage(51, dspCost_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNodeSignBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBatchCodeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, dataHour_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getStatTimeBytes());
      }
      for (int i = 0; i < dspCost_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(51, dspCost_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.emarbox.dsp.api.domain.DspCostRequest.internal_static_campaign_DspCostRequestInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.emarbox.dsp.api.domain.DspCostRequest.internal_static_campaign_DspCostRequestInfo_fieldAccessorTable;
      }
      
      // Construct using com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDspCostFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nodeSign_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        batchCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dataDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        dataHour_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        statTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        if (dspCostBuilder_ == null) {
          dspCost_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          dspCostBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo.getDescriptor();
      }
      
      public com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo getDefaultInstanceForType() {
        return com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo.getDefaultInstance();
      }
      
      public com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo build() {
        com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo buildPartial() {
        com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo result = new com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeSign_ = nodeSign_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.batchCode_ = batchCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataDate_ = dataDate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dataHour_ = dataHour_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.statTime_ = statTime_;
        if (dspCostBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            dspCost_ = java.util.Collections.unmodifiableList(dspCost_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.dspCost_ = dspCost_;
        } else {
          result.dspCost_ = dspCostBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo) {
          return mergeFrom((com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo other) {
        if (other == com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo.getDefaultInstance()) return this;
        if (other.hasNodeSign()) {
          setNodeSign(other.getNodeSign());
        }
        if (other.hasBatchCode()) {
          setBatchCode(other.getBatchCode());
        }
        if (other.hasDataDate()) {
          setDataDate(other.getDataDate());
        }
        if (other.hasDataHour()) {
          setDataHour(other.getDataHour());
        }
        if (other.hasStatTime()) {
          setStatTime(other.getStatTime());
        }
        if (dspCostBuilder_ == null) {
          if (!other.dspCost_.isEmpty()) {
            if (dspCost_.isEmpty()) {
              dspCost_ = other.dspCost_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureDspCostIsMutable();
              dspCost_.addAll(other.dspCost_);
            }
            onChanged();
          }
        } else {
          if (!other.dspCost_.isEmpty()) {
            if (dspCostBuilder_.isEmpty()) {
              dspCostBuilder_.dispose();
              dspCostBuilder_ = null;
              dspCost_ = other.dspCost_;
              bitField0_ = (bitField0_ & ~0x00000020);
              dspCostBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDspCostFieldBuilder() : null;
            } else {
              dspCostBuilder_.addAllMessages(other.dspCost_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getDspCostCount(); i++) {
          if (!getDspCost(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nodeSign_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              batchCode_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dataDate_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              dataHour_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              statTime_ = input.readBytes();
              break;
            }
            case 410: {
              com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder subBuilder = com.emarbox.dsp.api.domain.DspCost.DspCostInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addDspCost(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string nodeSign = 1;
      private java.lang.Object nodeSign_ = "";
      public boolean hasNodeSign() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNodeSign() {
        java.lang.Object ref = nodeSign_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nodeSign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNodeSign(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeSign_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeSign() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeSign_ = getDefaultInstance().getNodeSign();
        onChanged();
        return this;
      }
      void setNodeSign(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        nodeSign_ = value;
        onChanged();
      }
      
      // optional string batchCode = 2;
      private java.lang.Object batchCode_ = "";
      public boolean hasBatchCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getBatchCode() {
        java.lang.Object ref = batchCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          batchCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBatchCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        batchCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearBatchCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        batchCode_ = getDefaultInstance().getBatchCode();
        onChanged();
        return this;
      }
      void setBatchCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        batchCode_ = value;
        onChanged();
      }
      
      // optional string dataDate = 3;
      private java.lang.Object dataDate_ = "";
      public boolean hasDataDate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDataDate() {
        java.lang.Object ref = dataDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dataDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDataDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataDate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataDate_ = getDefaultInstance().getDataDate();
        onChanged();
        return this;
      }
      void setDataDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        dataDate_ = value;
        onChanged();
      }
      
      // optional int64 dataHour = 4;
      private long dataHour_ ;
      public boolean hasDataHour() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getDataHour() {
        return dataHour_;
      }
      public Builder setDataHour(long value) {
        bitField0_ |= 0x00000008;
        dataHour_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataHour() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dataHour_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string statTime = 5;
      private java.lang.Object statTime_ = "";
      public boolean hasStatTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getStatTime() {
        java.lang.Object ref = statTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          statTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStatTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        statTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        statTime_ = getDefaultInstance().getStatTime();
        onChanged();
        return this;
      }
      void setStatTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        statTime_ = value;
        onChanged();
      }
      
      // repeated .campaign.DspCostInfo dspCost = 51;
      private java.util.List<com.emarbox.dsp.api.domain.DspCost.DspCostInfo> dspCost_ =
        java.util.Collections.emptyList();
      private void ensureDspCostIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          dspCost_ = new java.util.ArrayList<com.emarbox.dsp.api.domain.DspCost.DspCostInfo>(dspCost_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.emarbox.dsp.api.domain.DspCost.DspCostInfo, com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder, com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder> dspCostBuilder_;
      
      public java.util.List<com.emarbox.dsp.api.domain.DspCost.DspCostInfo> getDspCostList() {
        if (dspCostBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dspCost_);
        } else {
          return dspCostBuilder_.getMessageList();
        }
      }
      public int getDspCostCount() {
        if (dspCostBuilder_ == null) {
          return dspCost_.size();
        } else {
          return dspCostBuilder_.getCount();
        }
      }
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfo getDspCost(int index) {
        if (dspCostBuilder_ == null) {
          return dspCost_.get(index);
        } else {
          return dspCostBuilder_.getMessage(index);
        }
      }
      public Builder setDspCost(
          int index, com.emarbox.dsp.api.domain.DspCost.DspCostInfo value) {
        if (dspCostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDspCostIsMutable();
          dspCost_.set(index, value);
          onChanged();
        } else {
          dspCostBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setDspCost(
          int index, com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder builderForValue) {
        if (dspCostBuilder_ == null) {
          ensureDspCostIsMutable();
          dspCost_.set(index, builderForValue.build());
          onChanged();
        } else {
          dspCostBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addDspCost(com.emarbox.dsp.api.domain.DspCost.DspCostInfo value) {
        if (dspCostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDspCostIsMutable();
          dspCost_.add(value);
          onChanged();
        } else {
          dspCostBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addDspCost(
          int index, com.emarbox.dsp.api.domain.DspCost.DspCostInfo value) {
        if (dspCostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDspCostIsMutable();
          dspCost_.add(index, value);
          onChanged();
        } else {
          dspCostBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addDspCost(
          com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder builderForValue) {
        if (dspCostBuilder_ == null) {
          ensureDspCostIsMutable();
          dspCost_.add(builderForValue.build());
          onChanged();
        } else {
          dspCostBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addDspCost(
          int index, com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder builderForValue) {
        if (dspCostBuilder_ == null) {
          ensureDspCostIsMutable();
          dspCost_.add(index, builderForValue.build());
          onChanged();
        } else {
          dspCostBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllDspCost(
          java.lang.Iterable<? extends com.emarbox.dsp.api.domain.DspCost.DspCostInfo> values) {
        if (dspCostBuilder_ == null) {
          ensureDspCostIsMutable();
          super.addAll(values, dspCost_);
          onChanged();
        } else {
          dspCostBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearDspCost() {
        if (dspCostBuilder_ == null) {
          dspCost_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          dspCostBuilder_.clear();
        }
        return this;
      }
      public Builder removeDspCost(int index) {
        if (dspCostBuilder_ == null) {
          ensureDspCostIsMutable();
          dspCost_.remove(index);
          onChanged();
        } else {
          dspCostBuilder_.remove(index);
        }
        return this;
      }
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder getDspCostBuilder(
          int index) {
        return getDspCostFieldBuilder().getBuilder(index);
      }
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder getDspCostOrBuilder(
          int index) {
        if (dspCostBuilder_ == null) {
          return dspCost_.get(index);  } else {
          return dspCostBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder> 
           getDspCostOrBuilderList() {
        if (dspCostBuilder_ != null) {
          return dspCostBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dspCost_);
        }
      }
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder addDspCostBuilder() {
        return getDspCostFieldBuilder().addBuilder(
            com.emarbox.dsp.api.domain.DspCost.DspCostInfo.getDefaultInstance());
      }
      public com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder addDspCostBuilder(
          int index) {
        return getDspCostFieldBuilder().addBuilder(
            index, com.emarbox.dsp.api.domain.DspCost.DspCostInfo.getDefaultInstance());
      }
      public java.util.List<com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder> 
           getDspCostBuilderList() {
        return getDspCostFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.emarbox.dsp.api.domain.DspCost.DspCostInfo, com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder, com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder> 
          getDspCostFieldBuilder() {
        if (dspCostBuilder_ == null) {
          dspCostBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.emarbox.dsp.api.domain.DspCost.DspCostInfo, com.emarbox.dsp.api.domain.DspCost.DspCostInfo.Builder, com.emarbox.dsp.api.domain.DspCost.DspCostInfoOrBuilder>(
                  dspCost_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          dspCost_ = null;
        }
        return dspCostBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:campaign.DspCostRequestInfo)
    }
    
    static {
      defaultInstance = new DspCostRequestInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:campaign.DspCostRequestInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_campaign_DspCostRequestInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_campaign_DspCostRequestInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026dsp-cost-request.proto\022\010campaign\032\016dsp-" +
      "cost.proto\"\227\001\n\022DspCostRequestInfo\022\020\n\010nod" +
      "eSign\030\001 \001(\t\022\021\n\tbatchCode\030\002 \001(\t\022\020\n\010dataDa" +
      "te\030\003 \001(\t\022\020\n\010dataHour\030\004 \001(\003\022\020\n\010statTime\030\005" +
      " \001(\t\022&\n\007dspCost\0303 \003(\0132\025.campaign.DspCost" +
      "InfoB,\n\032com.emarbox.dsp.api.domainB\016DspC" +
      "ostRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_campaign_DspCostRequestInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_campaign_DspCostRequestInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_campaign_DspCostRequestInfo_descriptor,
              new java.lang.String[] { "NodeSign", "BatchCode", "DataDate", "DataHour", "StatTime", "DspCost", },
              com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo.class,
              com.emarbox.dsp.api.domain.DspCostRequest.DspCostRequestInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.emarbox.dsp.api.domain.DspCost.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
